### ISSUE TITLE
DragDropSwipeRecyclerview does not recycle when is within NestedScrollView

### ISSUE THREAD

**Issue by paolovalerdi** [ernestoyaquello/DragDropSwipeRecyclerview#22]
I've been trying to use the recycler view within a NestedScrollView but it seems to lose all of the recycle-ability, I've searched around stack overflow and I've tried enabling/disabling isNestedScrollEnabled but doesn't seem to work. 
Normal RecyclerView works just normal in nestedScroll View

**Comment by ernestoyaquello** [comment]
What you are describing is an [old, known problem](https://stackoverflow.com/a/45657520/3891038) developers face when using a recycler view inside a nested scroll view. Since the nested scroll view needs to take control over the scrolling behaviour, it needs to know the size of its content (i.e., the size of the recycler view), which forces the system to render the recycler view entirely from the beginning. This is fine when you don't have many items, but it can become problematic when you do.

I will close the issue because this is not a bug in the library – this behaviour is normal and to be expected in any recycler view.

**Comment by paolovalerdi** [comment]
You're right, I was curious because actually, you can actually use the recyclerview within the nestedscrollview, but it has to be set to horizontal orientation and it will recycle without issues. 
Just one more question, does the scroll listener works to achieve [this sort of thing](https://github.com/ksoichiro/Android-ObservableScrollView)?

**Comment by ernestoyaquello** [comment]
Unfortunately, the scroll listener of this library is just a wrapper for the original one that recyclerviews already include, so it doesn't do anything special.

**Comment by paolovalerdi** [comment]
What a bummer, thank you so much for your quick responses.

**Comment by ernestoyaquello** [comment]
You can do everything that is shown in those GIFs using a `CoordinatorLayout`, so there is no need to use that library – unless you want to do something very odd and specific.
