### ISSUE TITLE
Some questions regarding the example app

### ISSUE THREAD

**Issue by alvindizon** [ernestoyaquello/DragDropSwipeRecyclerview#30]
I noticed a few things in your example app:

1. You set the ```divider``` and ```item_layout``` via XML, but at the same time, the ```BaseListFragment``` subclasses set the ```divider``` and ```item_layout``` programmatically. Should users follow this? If this is the case the README should be updated since the README only talks about setting it in via XML.

2. Should we implement the same logic found  in ```onItemAddedListener``` in the ```BaseListFragment```, in order to add new items to the ```RecyclerView```? Specifically, I'm puzzled as to why you had to call ```adapter.insertItem(position, item)```--does this mean the adapter doesn't hold a reference to the list that was passed to its constructor?

3. In ```fragment_vertical_list.xml```, why are you setting ```behind_swiped_item_bg_color``` to ```@color/swipeBehindBackground```, but on ```VerticalListFragment```'s ```setupLayoutBehindItemLayoutOnSwiping``` method, you are setting ```behindSwipedItemBackgroundColor``` to ```@null```? Why are you duplicating the setting of the color?

**Comment by ernestoyaquello** [comment]
1. You can set those properties either via code or via XML (if you change their values via code after setting them in XML, then the XML values will get replaced). In general, unless you need to define those properties or change them dynamically like in the demo app, the most common approach would be to set them only once via XML, but ultimately it is up to you.

2. The adapter does hold a reference to the list (you can see it in the code), but those methods that you mention are the ones that should be used when updating the list, as they take care of applying the changes and notifying the list about it.

3. Going back to 1., the demo app is not a perfect example of how to use the library, but an application that shows its features and capabilities. Hence, the reason why the value of that property gets replaced in code is because the demo app offers the user the possibility of switching between having a background behind swiped items and not having it. In a standard application, though, the value would be set once via XML and it would never be changed in code.

I hope this clears things up, but please let me know if you need more help. Thanks for commenting!
