### ISSUE TITLE
New features - drag on long click & drag item animator

### ISSUE THREAD

**Issue by flaringapp** [ernestoyaquello/DragDropSwipeRecyclerview#32]
Hi! 
The first thing I want to mention is it would be nice if you add an option to start dragging on long click (where the current touch listener in TouchHelper is)
Also it'd be a great thing if you add a feature to animate dragged view (kinda DragViewAnimator interface) (For example to scale view up on drag started and down on ended)

**Comment by ernestoyaquello** [comment]
I cannot promise anything, but I will take a look at these suggestions and see if they can be implemented without compromising the previous functionality or over-complicating the library API. Thanks for the suggestions!

**Comment by ernestoyaquello** [comment]
Started work on [this branch](https://github.com/ernestoyaquello/DragDropSwipeRecyclerview/tree/feature/32-long-tap-to-drag-and-dragging-animation).

**Comment by ernestoyaquello** [comment]
After taking a look at the dragging animations, I think they are already quite easy to implement in this library: all you need to do is to start them and stop them in your adapter inside `onDragStarted(...)` and `onDragFinished(...)`. I could include a default one to be used optionally, but since these animations aren't a standard practice, I will leave it up to each developer to implement their own if they wish.

On the other hand, the feature to use a long click to start the dragging action has been implemented and is now available in the [latest version of the app](https://github.com/ernestoyaquello/DragDropSwipeRecyclerview/releases/tag/v0.5.1). Thanks again for the suggestion!
