### ISSUE TITLE
Difficulty creating views of different types

### ISSUE THREAD

**Issue by SamueldaCostaAraujoNunes** [ernestoyaquello/DragDropSwipeRecyclerview#57]
My recycler, receives some different types of item views, in my current implementation, I use the viewType inside onCreateViewHolder, to differentiate and inflate different layouts. I wonder if it is possible to do this with your library?

**Comment by ernestoyaquello** [comment]
This might be a tricky one, given that the library relies heavily on the assumption that there will only be one item layout in order to facilitate the implementation. As a workaround, you can use the same layout for all the items and then show or hide different views depending on the item type (not ideal, I know, but it'd do the trick).

I will take a look to see if there is a way for me to make this a possibility, but it is likely that it won't actually be possible.

**Comment by ernestoyaquello** [comment]
So, I have been poking around with this, and while it is technically possible, there are some caveats. If you want to do it, this is what you need to do:

```kotlin
override fun getItemViewType(position: Int): Int {
    // Apply your logic here to return the appropriate item type value
    return position % 2
}

// Make sure you override this method with your implementation
override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): ViewHolder {
    return when (viewType) {
        0 -> EvenItemViewHolder(parent)
        else -> OddItemViewHolder(parent)
    }
}

// This method still needs to be implemented, but it won't be called
override fun getViewHolder(itemView: View): ViewHolder {
    throw NotImplementedError()
}
```

Now, the problem with this is that dragging will stop working as soon as the item being dragged becomes a different type of item and changes its layout. But if that's not a problem for your specific implementation, then the code above should work without issues.

I hope that helps, and sorry for the delay!
